"""
Tests for scenario registry functions.

Tests bug fixes and correct behavior of registry functions.
"""

import pytest
from socialsim4.core.scenarios.registry import get_all_scenarios, ALL_SCENARIOS


class TestScenarioRegistry:
    """Test scenario registry functions."""

    def test_get_all_scenarios_does_not_mutate_original(self):
        """Calling get_all_scenarios() should not mutate ALL_SCENARIOS."""
        # Find a sociology scenario before calling get_all_scenarios
        sociology_scenario = None
        for scenario in ALL_SCENARIOS:
            if scenario.get("category_actions") == "sociology":
                sociology_scenario = scenario
                break

        if sociology_scenario is None:
            pytest.skip("No sociology scenarios found")

        # Record the original type
        original_type = type(sociology_scenario["category_actions"]).__name__
        assert original_type == "str", f"Expected str, got {original_type}"

        # Call get_all_scenarios - this might mutate if bug exists
        _ = get_all_scenarios()

        # Check that the original scenario wasn't mutated
        after_type = type(sociology_scenario["category_actions"]).__name__
        assert after_type == "str", \
            f"Scenario was mutated from str to {after_type}!"


class TestGraphColoringScenario:
    """Test Graph Coloring scenario structure."""

    def test_graph_coloring_has_no_graph_generation_params(self):
        """GRAPH_COLORING should not have graph_type or edge_probability params.

        Graphs are created in the frontend via NetworkEditorModal, not generated by the backend.
        """
        from socialsim4.core.scenarios.registry import GRAPH_COLORING

        param_ids = [p["id"] for p in GRAPH_COLORING.get("parameters", [])]

        assert "graph_type" not in param_ids, \
            "graph_type should be removed - graphs come from frontend"
        assert "edge_probability" not in param_ids, \
            "edge_probability should be removed - graphs come from frontend"

    def test_graph_coloring_has_configurable_choices(self):
        """GRAPH_COLORING should allow users to configure the choices.

        The design specifies that users should be able to set what options
        the LLM can choose (colors by default, but could be other things).
        """
        from socialsim4.core.scenarios.registry import GRAPH_COLORING

        # Check that there's a parameter for configuring choices
        param_ids = [p["id"] for p in GRAPH_COLORING.get("parameters", [])]

        assert "choices" in param_ids or "colors" in param_ids, \
            "GRAPH_COLORING should have a 'choices' or 'colors' parameter for configuring options"
